### ISSUE TITLE
Failed Cache Storage returning HTTP 200

### ISSUE THREAD

**Issue by aaronmassicotte** [falcondev-oss/github-actions-cache-server#69]
Users were uploading cache but the server was logging an error

https://github.com/falcondev-oss/github-actions-cache-server/blob/dev/lib/storage/index.ts#L134C1-L135C1

```
[cache-server]  ERROR  Commit: Failed to commit cache for id 2967078670 ENAMETOOLONG: name too long, open '.data/storage/filesystem/[...REDACTED]'

  at async open (node:internal/fs/promises:639:25)
  at async Object.writeFile (node:internal/fs/promises:1212:14)
  at async Object.upload (server/chunks/runtime.mjs:5511:9)
  at async Object.commitCache (server/chunks/runtime.mjs:5732:11)
  at async handler (server/chunks/routes/_token/_apis/artifactcache/caches/_cacheId_.post.mjs:50:5)
  at async _callHandler (server/chunks/runtime.mjs:2712:16)
  at async Object.handler (server/chunks/runtime.mjs:2832:19)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)
```

In the Github Job, it says 

```
Cache Size: ~16 MB (16853466 B)
Cache saved successfully
Cache saved with key: [...REDACTED]
```

This is misleading, because it will later result in a CACHE MISS, despite appearing to have been correctly stored

**Comment by LouisHaftmann** [comment]
Thanks for reporting this! 🙏 

Will be fixed in the next release.

**Comment by LouisHaftmann** [comment]
Fixed in https://github.com/falcondev-oss/github-actions-cache-server/releases/tag/v4.0.0
