### ISSUE TITLE
Errors during multipart-upload

### ISSUE THREAD

**Issue by kuhnroyal** [falcondev-oss/github-actions-cache-server#81]
Running 4.0.0 with file system storage results in errors in `completeMultipartUpload`.
Where are the temp files stored? Do we maybe need another volume mapping?

```
github-cache  | [cache-server]  ERROR  Response: POST /<secret_token>/_apis/artifactcache/caches/8342711713 > 500
github-cache  |  EXDEV: cross-device link not permitted, rename 'github-actions-cache-serverfOpaoM/ba046d31-b085-4dea-b06a-28fd0e798c83' -> '.data/storage/filesystem/f1ea6b280e04ddffa0f679c23faf5d11fe4f59f2'
github-cache  | 
github-cache  |   at async Object.rename (node:internal/fs/promises:783:10)
github-cache  |   at async Object.completeMultipartUpload (server/chunks/runtime.mjs:5669:9)
github-cache  |   at async server/chunks/runtime.mjs:6007:11
github-cache  |   at async server/node_modules/kysely/dist/esm/kysely.js:412:32
github-cache  |   at async DefaultConnectionProvider.provideConnection (server/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
github-cache  |   at async Object.commitCache (server/chunks/runtime.mjs:6000:9)
github-cache  |   at async handler (server/chunks/routes/_token/_apis/artifactcache/caches/_cacheId_.post.mjs:48:5)
github-cache  |   at async _callHandler (server/chunks/runtime.mjs:2737:16)
github-cache  |   at async Object.handler (server/chunks/runtime.mjs:2857:19)
github-cache  |   at async Server.toNodeHandle (server/chunks/runtime.mjs:3128:7)
```

**Comment by LouisHaftmann** [comment]
Should be fixed in https://github.com/falcondev-oss/github-actions-cache-server/releases/tag/v4.0.1

**Comment by kuhnroyal** [comment]
Thanks! Seems to work.
